### PR TITLE
Attempt at sha1 implementation

### LINKED ISSUE #20: timestamp OR sha1?
Current behavior is that it won't re-run a script if it has the same name. Which is a feature, no doubt, but I'm wondering if other behavior can be added for `login-once`'s, maybe via an `optparse`-included option like '--trigger', to match a sha1? Therefore updating the login-once script would cause a fresh run. Normal warnings about trying to make sure checks are in place so this doesn't cause undesirable behavior is warranted, but seems advantageous to at least support as an arg: temporarily override the launchA for that flag, change it back after compliance is met.
Scope creep?

### PR DESCRIPTION
**Pull request by clburlison**
Fix #20 

Ideally [L250-258](https://github.com/clburlison/outset/blob/b9b5d7eba06b3ef468cd127fedec61583c844e58/outset#L250-L263) wouldn't duplicate code however I think it is easier to see what is happening as is. 

What changed:
- All new 'login-once' scripts will now store a sha1 hash and date key inside of an array
- If Line 2 of any script contains 'True' (case sensitive) outset will make sure the hashs match...if they don't the script will rerun.
- Start using this functionality immediately by adding True somewhere on line 2

~~We could do something close to this for @erikng 's new users only request. On line three if 'True' only run for new users? Also, not 100% sold on this implementation but it was the easiest way to add the functionality while being backwards compatible.~~

_edit:_
The more I look at this pull, I realize this resolves both issues brought up in #20. If the `True` string isn't on line two, new users will still get an updated script ran but present users will not have the script re-ran. it might be a better call to make the search string `Update = True` instead of just `True`. Less chance of accident. 
_end_edit_:

``` bash
#!/bin/bash
# Update = True
# my super awesome script
...
```

I can add documentation and any changes you recommend. Thoughts?

cc: @arubdesu, @erikng

### CODE REVIEW

**Comment by mholtrlc** [comment]
what if instead of requiring it to be on line 2 you look for a specific variable to equal TRUE.  It could then be more easily extended for other trigger options as well

**Comment by clburlison** [comment]
That becomes more problematic. Retrieving the variable from ruby, bash, and python script, all in a format that python likes. Getting the variables to export out reliably worked but created more code...I could have been doing it wrong. Feel free to show samples.  :smiley:

**Comment by mholtrlc** [comment]
gotchya.  My foray into Ruby and Python has just been in the last few months while building out our mac management platform to accomplish more than our original setup of just Munki so was just tossing out the idea.

**Comment by chilcote** [comment]
went a different direction than using checksums.

**Pull request closed without merging**
