### PR TITLE
Fixes for macOS 10.13 compatibility.

### PR DESCRIPTION
**Pull request by carlashley**

### CODE REVIEW

**Comment by erikng** [comment]
@carlashley is this a cosmetic fix or did it actually break? I use chef to install profiles and it's currently working using the IF flags on 10.13.

**Comment by carlashley** [comment]
The `-IF` flags work fine in 10.13, however the `man` for `profiles` in 10.13 advises:
```
Note that the command parameters have changed starting in version 5.0 of
this tool, but the older options are still valid and can also be used.
Use the man profiles.old(1) page to view the old parameters.  These older
style options will not be updated to provide support for some of the
newer profiles tool features, so it's suggested you move to use the new
parameter structure.
```
What this actually means for any future macOS release after 10.13 is unknown at this stage.

**Comment by erikng** [comment]
Awesome. Looks like lots of tools will be impacted by this.

**Comment by chilcote** [comment]
I'm okay with future proofing.

**Comment by erikng** [comment]
Agreed. Time to fix things!

**Pull request merged**
